### ISSUE TITLE
GPLv2 license — intentionally?

### ISSUE THREAD

**Issue by grray** [KWARC/rust-libxml#13]
Maybe, as it is library, it will be better to use LGPL license, so non-GPL projects could use it? Now, even GPLv3 project can't use it, if it is "GPLv2 only" https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility.

**Comment by dginev** [comment]
That's a fair point. I would be in favour of actually keeping the original libxml license, to stay in the spirit of the project. (they're using MIT). Changing that now...

**Comment by dginev** [comment]
Done. I don't recall why we had GPL originally (I know our KWARC group prefers it, but I personally get happier the closer one gets to the public domain).

MIT license it is!
