### ISSUE TITLE
FreeBSD instructions

### ISSUE THREAD

**Issue by rudolphfroger** [KWARC/rust-libxml#130]
Hi,

Here are FreeBSD instructions for in the `README.md`:

```sh
$ pkg install libxml2
$ LIBXML2=/usr/local/lib/libxml2.so cargo build
```

Btw, it would be nice if the crate could be build without setting an environment variable. Removing the `panic!("Could not find libxml2.")` from `build.rs` enables this on FreeBSD.

**Comment by dginev** [comment]
I am not a FreeBSD user so I may be missing something obvious. The ENV variable is only needed when the actual attempt at finding libxml2.so fails. For unix systems we have an actual attempt to find it via `pkg_config`:

https://github.com/KWARC/rust-libxml/blob/23804509dacb93dc5b9df76d1155fc41fb2cd349/build.rs#L31-L36


Is this not workable on FreeBSD? If so, what is a usual alternative?
Or do we need to add `, target_os = "freebsd"` to the cfg enumeration?

**Comment by rudolphfroger** [comment]
After some more fiddling around, I found out that I need to install the `pkgconf` package on FreeBSD, which provides `pkg-config`. So the instructions for FreeBSD actually are:

```
$ pkg install libxml2 pkgconf
$ cargo build
```

It would be nice if you could add that to the `README.md`

**Comment by dginev** [comment]
Thank you for contributing this @rudolphfroger !
