### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by greyblake** [KWARC/rust-libxml#40]
Hey, thank you for the nice crate! So far it's the only solution I found that works well with all types of crazy HTMLs and supports XPath as expected.  

I got couple times frustrated with the situation about XML parsers in Rust ecosystem, but just tried out you bindings and they work just like magic! :+1: :heart:

**Comment by dginev** [comment]
Hey @greyblake ! Thank you for the nice words.

I personally continue to believe Rust will have a libxml-killer implemented natively in pure rust, and it may beat it in both coverage in performance :+1: But your story is exactly why this crate was started - we had a couple of important projects that relied heavily on libxml features (and its eager processing model), so it would have been unfeasible to even start porting them if we had to implement every missing piece of libxml in one of the main XML crates in Rust.

Luckily `bindgen` did most of the work w.r.t coverage, we are still exploring what the best ergonomics are for the public API. Feel free to request missing pieces you need, or even better - to try your hand at adding the missing methods and filing small PRs. :1st_place_medal:
