### ISSUE TITLE
XmlSec sister project

### ISSUE THREAD

**Issue by lweberk** [KWARC/rust-libxml#66]
Hi,

just wanted to drop a message informing of the newly birthed [xmlsec](https://github.com/voipir/rust-xmlsec) wrapper, which is bases itself partly on this one and expands it by XML signing, signode templating and verification functionalities.

Have fun!

**Comment by dginev** [comment]
Thanks for announcing! I also have a largely placeholder [libxslt](https://crates.io/crates/libxslt) wrapper published, to build an easy path forward on the stylesheet front. And another bit of ecosystem outlook is that the kind folks of [C2Rust](https://c2rust.com/) are working on a full translation of libxml into Rust, which is looking pretty hopeful, so we may eventually end up with no C toolchain at all.

**Comment by dginev** [comment]
Maybe it would be good to reference the reverse dependencies in the README at some point, as a way of advertising such projects:
https://crates.io/crates/libxml/reverse_dependencies

Closing here for now, since it's not exactly an issue :+1:
