### ISSUE TITLE
dtd suport

### ISSUE THREAD

**Issue by cortopy** [KWARC/rust-libxml#69]
I just bumped into this crate. Thank you for this! 

I can see that the latest work you've been doing is around xml schemas. With this in mind, are you planning to add bindings for DTD validation?

**Comment by dginev** [comment]
Happy you found the crate helpful!

Exposing all DTD features of libxml is definitely a "want-to-have" for this wrapper, and I will happily accept such enhancements.

That said, there is no active roadmap for crate development at the moment, and the previous schema work was introduced on a volunteer basis. So sadly I can't offer any personal support here in development - but I will make time to review and merge related PRs, so you are most welcome to take a stab - or recruit a DTD expert who wants a chance to learn a little about Rust.

**Comment by cortopy** [comment]
Thank you for the clarification! I would love to contribute but I'm only asking as a Rust noob who is assessing whether using Rust for xml is as good as I'm used to. And I'm definitely not an expert on DTDs!!

Thanks again for the crate
