### ISSUE TITLE
Powerpc/ARM doesn't compile

### ISSUE THREAD

**Issue by mtthw-meyer** [KWARC/rust-libxml#70]
From what I gather this is probably due to the definitions here [here](https://doc.rust-lang.org/src/std/os/raw/mod.rs.html#12). Short version is the type needs to be defined depending on the target or this won't work for powerpc/ARM platforms. I'm not sure if it's possible to setup a gist for targets like this or I'd create one.

```
error[E0308]: mismatched types
  --> /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/libxml-0.2.13/src/schemas/parser.rs:51:60
   |
51 |     let parser = unsafe { bindings::xmlSchemaNewParserCtxt(path_ptr) };
   |                                                            ^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*const i8`

error[E0308]: mismatched types
  --> /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/libxml-0.2.13/src/schemas/validation.rs:61:66
   |
61 |     let rc = unsafe { bindings::xmlSchemaValidateFile(self.ctxt, path_ptr, 0) };
   |                                                                  ^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*const i8`

error: aborting due to 2 previous errors
```

**Comment by dginev** [comment]
Interesting! I have never developed for ARM, didn't even occur to me someone would like to use this libxml wrapper over there.

Do you know if there is a best practice for rust-on-ARM development one could read? Happy to facilitate some best-practice approach to supporting multiple platforms.

**Comment by mtthw-meyer** [comment]
I'm not aware of the "right" way to deal with it between platforms. Maybe just use c_char since will change based on the platform if that works.

**Comment by dginev** [comment]
Sounds simple enough. @mtthw-meyer could you check if there is an improvement with the latest master branch? I refactored as you suggested.

**Comment by mtthw-meyer** [comment]
Took me a bit to figure out how to specify the repo instead of crates.io. It compiles with those changes.

**Comment by dginev** [comment]
Thank you for validating! I have pushed out a minor release `v0.2.14`, which you can use directly from crates.io. Feel free to report any other issues you may encounter.
