### ISSUE TITLE
Removal of Error trait for XmlParseError

### ISSUE THREAD

**Issue by lweberk** [KWARC/rust-libxml#75]
Happened in e10459c436e2cd3fe31ba6d904fd384d5b923d1a. Any particular reason for this?

**Comment by dginev** [comment]
Seemed unnecessary since I was removing `.description()`. I can re-add an empty implementation if it grants anything?

**Comment by dginev** [comment]
Just done in 67bfb5d15474b62ead6ce9fc0583527e8a37b0a1 .

As to the reason for removal, it slipped my mind that someone may be using this in generic code, and I was in a clutter-removal mode.

**Comment by lweberk** [comment]
Yeah it broke my downstream error chaining, since I depended on casting to dyn Error for my own <dyn Error>.source().

Thanks for the quick fix!
