### ISSUE TITLE
Build failing on MacOS X

### ISSUE THREAD

**Issue by ballsteve** [KWARC/rust-libxml#88]
When I try using the libxml crate on a Mac OS X laptop, I get the following build error:

  thread 'main' panicked at 'Could not find libxml2.', /Users/balls/.cargo/registry/src/github.com-1ecc6299db9ec823/libxml-0.3.0/build.rs:25:5

This appears to be similar to other issues (#81, #72), but they were on Windows so I don't think the answer/resolution will be the same.

Is the crate looking for an existing installation of libxml2? If so then how can I point the build to it?

**Comment by ballsteve** [comment]
This issue is now resolved. The steps taken were as follows:

I downloaded, built and installed the libxml2-2.9.12 tarball, using --prefix=/usr/local

Set environment variable LIBXML2=/usr/local/lib/pkgconfig/libxml-2.0.pc; export LIBXML2

cargo build was then successful.

I would suggest adding these steps to the README.

**Comment by dginev** [comment]
Thanks for troubleshooting that installation @ballsteve ! I am surprised, I would've expected Mac OS to be successful via the pkg-config route. I am not a Mac user myself, but pkg-config seems widely available on the various package managers.

The resolution path you've taken was meant for embedded devices that can't add extra dependencies, so while I'm happy you got things working, it's also too manual to be satisfied...

**Comment by ballsteve** [comment]
Further to the above resolution, I also had to create a symbolic link for /usr/local/lib/libxml-2.0.dylib to libxml2.2.dylib. So that's even more manual intervention required!

**Comment by hurlenko** [comment]
Thanks to @ballsteve, here are the steps it took me to compile this crate on macOS:

1. `brew install libxml2` # v 2.9.12 in my case
2. `ln -s /usr/local/Cellar/libxml2/2.9.12/lib/libxml2.2.dylib /usr/local/lib/libxml-2.0.dylib`
3. `export LIBXML2=/usr/local/Cellar/libxml2/2.9.12/lib/pkgconfig/libxml-2.0.pc`
4. `cargo build`

Adding these steps, along with the [windows compilation instruction](https://github.com/KWARC/rust-libxml/issues/81#issuecomment-760364976) to the README would be really nice 🙂
