### ISSUE TITLE
Link issue with Homebrew on Linux

### ISSUE THREAD

**Issue by jcamiel** [KWARC/rust-libxml#91]
Hi,

First of all, thank you for your crate, it's really invaluable.

I'm trying to build a Homebrew formula for [Hurl](https://hurl.dev) (in Homebrew vocabulary, a formula is a ruby script to compile and install binaries). Hurl uses libxml crate for xpath evaluation. With a standard setup (lixmb2 installed with apt-get for instance), everything is ok and we can build and run our cli without any problem.

On macOS, I don't have any problem and my formula is building.

On Linux (Homebrew requires formulae to be available on Linux), I've some problem building my binary.

In this setup, libxml2 is provided by Homebrew, and installed in `/home/linuxbrew/.linuxbrew/Cellar/libxml2/2.9.12`

The directory contains:

```
$ ls /home/linuxbrew/.linuxbrew/Cellar/libxml2/2.9.12
AUTHORS  ChangeLog  Copyright  INSTALL_RECEIPT.json  NEWS  README  TODO  bin  include  lib  share
```

In lib directory:

```
$ find lib
lib/libxml2.so
lib/libxml2.a
lib/libxml2.so.2
...
lib/pkgconfig/libxml-2.0.pc
...
```

(note the name of pkgconfig file: `libxml-2.0.pc`)

When I'm building the Brew formula, I call `cargo install --path packages/hurl --locked` in the Homebrew install script.

If I try to build as it, I've a compilation error (rightfully raised by libxml/build.rs):

```
thread 'main' panicked at 'Could not find libxml2.', /root/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libxml-0.3.0/build.rs:25:5
```

Then, I set the LIBXML2 env variable to the Brew libxml2 pkgconfig file:

```
export LIBXML2=/home/linuxbrew/.linuxbrew/opt/libxml2/lib/pkgconfig/libxml-2.0.pc
```

Now, I pass the compilation phase, but I've an error at link:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/
  ...
  "-Wl,-Bdynamic" "-lxml-2.0" "-lssl" 
  ...
    = note: /home/linuxbrew/.linuxbrew/bin/ld: cannot find -lxml-2.0
          collect2: error: ld returned 1 exit status
```

The link flag `-lxml-2.0` seems suspicious, and, if my understanding is good, this flag is build from the LIBXML2 environment 
variable in libxml/build.rs:

https://github.com/KWARC/rust-libxml/blob/40020e15b726c27dc4435e9d104a9799f4c77f46/build.rs#L2-L10

Now, if a rename the pkgconfig to be `/home/linuxbrew/.linuxbrew/opt/libxml2/lib/pkgconfig/libxml2.pc` (instead of `libxml-2.0.pc`), the link phase is good and I can build my binary....

I don't know if this is an issue of the libxml2 Brew Formula, and certainly this setup is rather unusual (build a rust projet on linux with c dependencies provided by Homebrew). Currently, I can't rename the libxml-2-0.pc as it's a readonly dependency provided by Homebrew. Do you have any idea on how I can "give" libxml crate the right build paths?

I've the impression (maybe naive), that we could explicitely pass the value of `cargo:rustc-link-lib` and `cargo:rustc-link-search` instead of deriving those values from LIBXML2...

Thank you,

Jc

**Comment by dginev** [comment]
Not a macOS user myself, so I'll encourage other users of the wrapper to volunteer some feedback here if possible. But hopefully we can find solution that keep the crate installation as turnkey -- requiring custom paths and other tweaks for each installation on specific operating systems somewhat defeats the reliance on pkg-config.

**Comment by jcamiel** [comment]
Thanks for the reply, 
If I understand you, in this configuration, I should not try to set LIBXML2, but see why pkg-config doesn't seem to find "libxml-2.0" with the Homebrew configuration in :

https://github.com/KWARC/rust-libxml/blob/40020e15b726c27dc4435e9d104a9799f4c77f46/build.rs#L29-L35

**Comment by dginev** [comment]
@jcamiel that would be helpful to know indeed.

**Comment by jcamiel** [comment]
I've added a kind of minimal setup to reproduce my problem, I try to narrow my issue:

1. A simple rust program that uses libxml crate (<https://github.com/jcamiel/testxml>):

src/main.rs:

```rust
use libxml::tree::Document;

fn main() {
    let doc_result = Document::new();
    assert!(doc_result.is_ok());
}
```

Cargo.toml
```toml
[package]
name = "testxml"
version = "0.1.0"
edition = "2021"

[dependencies]
libxml = "0.3.0"
```

2. A simple Brew formula (<https://github.com/jcamiel/homebrew-testxml>):

```ruby
class Testxml < Formula
  desc "Test xml"
  url "https://github.com/jcamiel/testxml/archive/refs/tags/0.0.1.tar.gz"
  sha256 "72c145617d9af341d332c330f164a987a11b6abe590522a8b675ccd8f00edb78"

  depends_on "rust" => :build

  on_linux do
      depends_on "libxml2" => :build
  end

  def install
      system "cargo", "install", *std_cargo_args(path: ".")
  end

end
```

3. Test this formula on macOS:

```
$ brew tap jcamiel/testxml
$ brew install testxml
$ testxml
```

4. Test this formula on Linux:

I use this Dockerfile to test a new Linux image:

```Dockerfile
FROM debian:bullseye

RUN apt-get update
RUN apt-get -y install curl \
    git \
    clang
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
```

Then, install the test formula:

```
$ brew tap jcamiel/testxml
$ brew install testxml
...
==> cargo install
Last 15 lines from /root/.cache/Homebrew/Logs/testxml/01.cargo:
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Could not find libxml2.', /root/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libxml-0.3.0/build.rs:25:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `testxml v0.1.0 (/tmp/testxml-20211212-10682-nobigf/testxml-0.0.1)`, intermediate artifacts can be found at `/tmp/testxml-20211212-10682-nobigf/testxml-0.0.1/target`
```

**Comment by jcamiel** [comment]
Hi @dginev,
With the help of the Homebrew community (and particularly @danielnachun), I can now build my Homebrew formula on Linux without any issue. The problem was in the formula, which was missing a dependy on `pkg-config` (the Homebrew dependency one), and specified `libxml2` as a build only dependency.

For the record, my minimal Rust application, with a Homebrew formula working on macOs and Linux:

src/main.rs:
```rust
use libxml::tree::Document;

fn main() {
    let doc_result = Document::new();
    assert!(doc_result.is_ok());
}
```

Cargo.toml:
```toml
[package]
name = "testxml"
version = "0.1.0"
edition = "2021"

[dependencies]
libxml = "0.3.0"
```

And the Homebrew formula:

```ruby
class Testxml < Formula
  desc "Test xml"
  url "https://github.com/jcamiel/testxml/archive/refs/tags/0.0.1.tar.gz"
  sha256 "72c145617d9af341d332c330f164a987a11b6abe590522a8b675ccd8f00edb78"

  depends_on "rust" => :build

  on_linux do
      depends_on "pkg-config" => :build
      depends_on "libxml2"
  end

  def install
      system "cargo", "install", *std_cargo_args(path: ".")
  end

end
```

Once again thank you very much for your crate!

**Comment by dginev** [comment]
Excellent news @jcamiel thanks for opening the issue and posting the resolution here, much appreciated!

Enjoy using the wrapper, I'm happy you found it useful!
